'$Serial: 5617 $ $Revision: #29 $';var d7=-1,h5=0,ie=0,h4=1,ia=2,eo=3,fs=4,
ib=5,ic=6,ee=7,fv=8,fw=9,id=10,fr=11,fu=12,ft=13;STATUS_NEW=h5;
STATUS_INPROGRESS=h4;STATUS_BADENCODING=ia;STATUS_BADPASSWORD=eo;
STATUS_BADHASH=fs;STATUS_DONE=d7;STATUS_SUCCESS=ie;STATUS_BADPOSTMARK=ib;
STATUS_BADSIGNATURE=ic;STATUS_TOOMANYBADPASSWORDS=ee;STATUS_INCOMPATIBLE=fv;
STATUS_PASSWORDCHANGED=fw;STATUS_NOUSERSELECTED=id;
